import { defineConfig } from 'tsdown'

export default defineConfig({
  entry: { index: 'index-src.ts' },
  outDir: '.',
  outExtensions: () => ({ js: '.js' }),
  format: ['cjs'],
  external: [
    'react',
    'react-dom',
    'react-redux',
    'redux',
    'redux-observers',
    'react-fontawesome',
    'electron',
    '@electron/remote',
    'i18next',
    'react-i18next',
    'lodash',
    '@blueprintjs/core',
    'immutable',
    'reselect',
    'classnames',
    'kcsapi',
    'views/create-store',
    'views/utils/selectors',
    'views/utils/game-utils',
    'views/components/etc/icon',
    'views/components/etc/avatar',
    'views/components/etc/overlay',
    'path-extra',
    'fs-extra',
    'bluebird',
  ],
  dts: false,
  clean: false,
  sourcemap: true,
  treeshake: true,
  minify: true,
  shims: false,
  target: false,
})
