var Parser,StringDecoder,stream,util
stream=require("stream"),util=require("util"),StringDecoder=require("string_decoder").StringDecoder,module.exports=function(){var t,i,s,n,o,e
if(3===arguments.length){if(n=arguments[0],o=arguments[1],t=arguments[2],"function"!=typeof t)throw Error("Invalid callback argument: "+JSON.stringify(t))
if("string"!=typeof n&&!Buffer.isBuffer(arguments[0]))return t(Error("Invalid data argument: "+JSON.stringify(n)))}else 2===arguments.length?("string"==typeof arguments[0]||Buffer.isBuffer(arguments[0])?n=arguments[0]:o=arguments[0],"function"==typeof arguments[1]?t=arguments[1]:o=arguments[1]):1===arguments.length&&("function"==typeof arguments[0]?t=arguments[0]:o=arguments[0])
return null==o&&(o={}),e=new Parser(o),null!=n&&process.nextTick(function(){return e.write(n),e.end()}),t&&(i=!1,s=o.objname?{}:[],e.on("readable",function(){var t,i
for(i=[];t=e.read();)o.objname?i.push(s[t[0]]=t[1]):i.push(s.push(t))
return i}),e.on("error",function(s){return i=!0,t(s)}),e.on("end",function(){return i?void 0:t(null,s)})),e},Parser=function(t){var i,s,n,o,e,r,h,l,u,p,a,m,f,c,d,_,g,w,x
null==t&&(t={}),t.objectMode=!0,this.options={}
for(w in t)x=t[w],this.options[w]=x
return stream.Transform.call(this,this.options),null==(i=this.options).rowDelimiter&&(i.rowDelimiter=null),null==(s=this.options).delimiter&&(s.delimiter=","),null==(p=this.options).quote&&(p.quote='"'),null==(a=this.options).escape&&(a.escape='"'),null==(m=this.options).columns&&(m.columns=null),null==(f=this.options).comment&&(f.comment=""),null==(c=this.options).objname&&(c.objname=!1),null==(d=this.options).trim&&(d.trim=!1),null==(_=this.options).ltrim&&(_.ltrim=!1),null==(g=this.options).rtrim&&(g.rtrim=!1),null==(n=this.options).auto_parse&&(n.auto_parse=!1),null==(o=this.options).auto_parse_date&&(o.auto_parse_date=!1),null==(e=this.options).relax&&(e.relax=!1),null==(r=this.options).relax_column_count&&(r.relax_column_count=!1),null==(h=this.options).skip_empty_lines&&(h.skip_empty_lines=!1),null==(l=this.options).max_limit_on_data_read&&(l.max_limit_on_data_read=128e3),null==(u=this.options).skip_lines_with_empty_values&&(u.skip_lines_with_empty_values=!1),this.lines=0,this.count=0,this.skipped_line_count=0,this.empty_line_count=0,this.is_int=/^(\-|\+)?([1-9]+[0-9]*)$/,this.is_float=function(t){return t-parseFloat(t)+1>=0},this.decoder=new StringDecoder,this.buf="",this.quoting=!1,this.commenting=!1,this.field="",this.nextChar=null,this.closingQuote=0,this.line=[],this.chunks=[],this.rawBuf="",this},util.inherits(Parser,stream.Transform),module.exports.Parser=Parser,Parser.prototype._transform=function(t,i,s){var n,o
t instanceof Buffer&&(t=this.decoder.write(t))
try{return this.__write(t,!1),s()}catch(o){return n=o,this.emit("error",n)}},Parser.prototype._flush=function(t){var i,s
try{return this.__write(this.decoder.end(),!0),this.quoting?void this.emit("error",new Error("Quoted field not terminated at line "+(this.lines+1))):(this.line.length>0&&this.__push(this.line),t())}catch(s){return i=s,this.emit("error",i)}},Parser.prototype.__push=function(t){var i,s,n,o,e,r,h
if(!this.options.skip_lines_with_empty_values||""!==t.join("").trim()){if(h=null,this.options.columns===!0)return this.options.columns=t,void(r="")
if("function"==typeof this.options.columns)return this.options.columns=this.options.columns(t),void(r="")
if(!this.line_length&&t.length>0&&(this.line_length=this.options.columns?this.options.columns.length:t.length),1===t.length&&""===t[0])this.empty_line_count++
else if(t.length!==this.line_length){if(!this.options.relax_column_count)throw null!=this.options.columns?Error("Number of columns on line "+this.lines+" does not match header"):Error("Number of columns is inconsistent on line "+this.lines)
this.skipped_line_count++}else this.count++
if(null!=this.options.columns){for(e={},s=n=0,o=t.length;o>n;s=++n)i=t[s],this.options.columns[s]!==!1&&(e[this.options.columns[s]]=i)
h=this.options.objname?[e[this.options.objname],e]:e}else h=t
return this.options.raw?(this.push({raw:this.rawBuf,row:h}),this.rawBuf=""):this.push(h)}},Parser.prototype.__write=function(t,i,s){var n,o,e,r,h,l,u,p,a,m,f,c,d,_,g,w,x,y,D,b,q,v,C
for(d=function(t){return function(i){return"function"==typeof t.is_int?t.is_int(i):t.is_int.test(i)}}(this),c=function(t){return function(i){return"function"==typeof t.is_float?t.is_float(i):t.is_float.test(i)}}(this),e=function(t){return function(i){var s
return t.options.auto_parse&&d(t.field)?t.field=parseInt(t.field):t.options.auto_parse&&c(t.field)?t.field=parseFloat(t.field):t.options.auto_parse&&t.options.auto_parse_date&&(s=Date.parse(t.field),isNaN(s)||(t.field=new Date(s))),t.field}}(this),g=this.options.trim||this.options.ltrim,v=this.options.trim||this.options.rtrim,t=this.buf+t,_=t.length,q=this.options.rowDelimiter?this.options.rowDelimiter.length:0,l=0,0===this.lines&&65279===t.charCodeAt(0)&&l++;_>l&&(i||(y=t.substr(l,_-l),!(!this.commenting&&_-l<this.options.comment.length&&this.options.comment.substr(0,_-l)===y||this.options.rowDelimiter&&q>_-l&&this.options.rowDelimiter.substr(0,_-l)===y||this.options.rowDelimiter&&this.quoting&&_-l<this.options.quote.length+q&&(this.options.quote+this.options.rowDelimiter).substr(0,_-l)===y||_-l<=this.options.delimiter.length&&this.options.delimiter.substr(0,_-l)===y||_-l<=this.options.escape.length&&this.options.escape.substr(0,_-l)===y)));)if(r=this.nextChar?this.nextChar:t.charAt(l),this.nextChar=_>l+1?t.charAt(l+1):"",this.options.raw&&(this.rawBuf+=r),null==this.options.rowDelimiter&&(this.quoting||"\n"!==r&&"\r"!==r?"\n"!==this.nextChar&&"\r"!==this.nextChar||(b=this.nextChar,w=l+2,this.raw&&(rawBuf+=this.nextChar)):(b=r,w=l+1),b&&("\r"===b&&"\n"===t.charAt(w)&&(b+="\n"),this.options.rowDelimiter=b,q=this.options.rowDelimiter.length)),this.commenting||r!==this.options.escape||(h=this.options.escape===this.options.quote,p=this.nextChar===this.options.escape,m=this.nextChar===this.options.quote,h&&!this.field&&!this.quoting||!p&&!m)){if(!this.commenting&&r===this.options.quote)if(this.quoting){if(o=this.options.rowDelimiter&&t.substr(l+1,this.options.rowDelimiter.length)===this.options.rowDelimiter,n=t.substr(l+1,this.options.delimiter.length)===this.options.delimiter,a=this.nextChar===this.options.comment,!this.nextChar||o||n||a){this.quoting=!1,this.closingQuote=this.options.quote.length,l++,i&&l===_&&(this.line.push(e(this.field)),this.field="")
continue}if(!this.options.relax)throw Error("Invalid closing quote at line "+(this.lines+1)+"; found "+JSON.stringify(this.nextChar)+" instead of delimiter "+JSON.stringify(this.options.delimiter))
this.quoting=!1,this.field=""+this.options.quote+this.field}else{if(!this.field){this.quoting=!0,l++
continue}if(this.field&&!this.options.relax)throw Error("Invalid opening quote at line "+(this.lines+1))}if(f=this.options.rowDelimiter&&t.substr(l,this.options.rowDelimiter.length)===this.options.rowDelimiter,(f||i&&l===_-1)&&this.lines++,C=!1,this.commenting||this.quoting||!this.options.comment||t.substr(l,this.options.comment.length)!==this.options.comment?this.commenting&&f&&(C=!0,this.commenting=!1):this.commenting=!0,u=t.substr(l,this.options.delimiter.length)===this.options.delimiter,this.commenting||this.quoting||!u&&!f)this.commenting||this.quoting||" "!==r&&"	"!==r?this.commenting?l++:(this.field+=r,l++):(g&&!this.field||(this.field+=r),i&&l+1===_&&(this.options.trim||this.options.rtrim)&&(this.field=this.field.trimRight()),l++)
else{if(f&&0===this.line.length&&""===this.field&&(C||this.options.skip_empty_lines)){l+=this.options.rowDelimiter.length,this.nextChar=t.charAt(l)
continue}if(v&&(this.closingQuote||(this.field=this.field.trimRight())),this.line.push(e(this.field)),this.closingQuote=0,this.field="",u&&(l+=this.options.delimiter.length,this.nextChar=t.charAt(l),i&&!this.nextChar&&(f=!0,this.line.push(""))),f){this.__push(this.line),this.line=[],l+=null!=(x=this.options.rowDelimiter)?x.length:void 0,this.nextChar=t.charAt(l)
continue}}if(!this.commenting&&this.field.length>this.options.max_limit_on_data_read)throw Error("Delimiter not found in the file "+JSON.stringify(this.options.delimiter))
if(!this.commenting&&this.line.length>this.options.max_limit_on_data_read)throw Error("Row delimiter not found in the file "+JSON.stringify(this.options.rowDelimiter))}else l++,r=this.nextChar,this.nextChar=t.charAt(l+1),this.field+=r,this.options.raw&&(this.rawBuf+=r),l++
if(i){if(v&&(this.closingQuote||(this.field=this.field.trimRight())),""!==this.field&&(this.line.push(e(this.field)),this.field=""),this.field.length>this.options.max_limit_on_data_read)throw Error("Delimiter not found in the file "+JSON.stringify(this.options.delimiter))
if(0===_&&this.lines++,this.line.length>this.options.max_limit_on_data_read)throw Error("Row delimiter not found in the file "+JSON.stringify(this.options.rowDelimiter))}for(this.buf="",D=[];_>l;)this.buf+=t.charAt(l),D.push(l++)
return D}
